In [ ]:
a=5
b=66
print(a+b)

71


In [ ]:
for i in range(5):
    print(i)

0
1
2
3
4


In [ ]:
n=int(input("enter a number"))
for i in range(n):
    print(i)

ValueError: invalid literal for int() with base 10: '`5'

In [ ]:
a=int(input("firstnumber"))

In [ ]:
#WAP TO PRINT SUM OF DIGIT OF A NUMBER
n=int(input("enter a number"))
sum=0
temp=n
while temp>0:
    sum=sum+temp%10
    temp=temp//10

print("sum of digits:",sum)

sum of digits: 9


In [ ]:
#wap to print factorial of a number
n=int(input("enter a number"))
fact=1
for i in range(1,n+1):
    fact=fact*i
print("factorial is:",fact)


fectorial is: 120


In [ ]:
#wap to check string is palindrome or not
s=input("enter a string")
if s==s[::-1]:
    print("palindrome")
else:
    print("not palindrome")

palindrome


In [ ]:
#wap to print multiplication table of a number
n=int(input("enter a number"))
for i in range(1,11):
    print(n,"*",i,"=",n*i)

5 * 1 = 5
5 * 2 = 10
5 * 3 = 15
5 * 4 = 20
5 * 5 = 25
5 * 6 = 30
5 * 7 = 35
5 * 8 = 40
5 * 9 = 45
5 * 10 = 50


In [ ]:
#wap to count words in a given string
s=input("enter a string")
words=s.split()
print("number of words:",len(words))

number of words: 1


In [ ]:
#wap to find if given number is armstrong or not
n=int(input("enter a number"))
sum=0
temp=n
while temp>0:
    digit=temp%10
    sum+=digit**3
    temp//=10
if sum==n:
    print("armstrong")
else:
    print("not armstrong")

In [ ]:
def yooo():
    print("heyy i am jarvis")

yooo()

heyy i am jarvis


In [ ]:
#wap to define function
def sum(a,b):
    print(a+b)
x=int(input("enter first number"))
y=int(input("enter second number"))
sum(x,y)

7


In [ ]:
#wap to funtion to convert decimal to binary
def decimal2binnary(n):
    if n>1:
        decimal2binnary(n//2)
    print(n%2,end="")
num=int(input("enter a number"))
decimal2binnary(num)

    

101

In [ ]:
#numpy array
import numpy as np
arr=np.array([1,2,3,4,5])
print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [ ]:
#use tuple to create numpy array
array=np.array((2,4,6,8,10,12))
print(array)

[ 2  4  6  8 10 12]


In [ ]:
#create a list ,with temperature vlaues
cvalues=[20.76,1.5,20.8,21.9,22.5,22.7,22.3,21.8,21.2,20.6,20.1]

In [ ]:
#convert values into 1D array
c=np.array(cvalues)
print(c)

[20.76  1.5  20.8  21.9  22.5  22.7  22.3  21.8  21.2  20.6  20.1 ]


#IMPORT NUMPY

In [ ]:
array1=np.array([[1,2,3],[4,5,6],[7,8,9]],dtype=float)
print(array1)
print(array1.ndim)
print(array1.shape) 
print(array1.itemsize)

[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]
2
(3, 3)
8


In [ ]:
import numpy as np
print(np.__version__)

2.1.3


In [ ]:
#creating 3d array using numpy function
import numpy as np
threeD=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(threeD)
print(threeD.ndim)
print(threeD.shape)
print(threeD.itemsize)
print(threeD.size)



[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
3
(2, 2, 3)
8
12


In [6]:
#to create a data frame usning pandas library that stores basic student details
import pandas as pd
data={'Name':['Aryan','John','Alice','Bob'],
      'degree':['B.Tech','M.Tech','PhD','BSc'],
      'store':[50, 60, 70, 80],
      'city':['Delhi','Mumbai','Bangalore','Hyderabad']}
#convert dictionary to data frame
studentdata=pd.DataFrame(data)
print(studentdata)

    Name  degree  store       city
0  Aryan  B.Tech     50      Delhi
1   John  M.Tech     60     Mumbai
2  Alice     PhD     70  Bangalore
3    Bob     BSc     80  Hyderabad


WORKING WITH IRIS DATASET
